### ISSUE TITLE
KEYEVENTF_EXTENDEDKEY

### ISSUE THREAD

**Issue by Datami555** [DavidRieman/SimWinInput#1]
Hello DavidRieman,

Thank you for your working. I'm using your code and I really like it but I found some issues here. The KEYEVENTF_EXTENDEDKEY flag does not mean that key is being pressed. I found some nice explain about this flag [here](https://stackoverflow.com/questions/21197257/keybd-event-keyeventf-extendedkey-explanation-required/)

Why does it matter... When I call KeyDown with modifier keys (Ctrl, Alt, Shift) it would be preceded by 0xE0 and then I call KeyUp with the same keycode above, it wouldn't work because these keycode are difference! So I have to pass KEYEVENTF_EXTENDEDKEY  |  KEYEVENTF_KEYUP to dwFlags and finally it released the Alt key which drives me crazy all day.

**Comment by DavidRieman** [comment]
Hi,

Sorry for the late response.  Somehow I was not marked in GitHub as Watching my own repository here, and just noticed this yesterday since I wasn't getting emails.

Thank you for filing this issue.  I've changed the KeyDown flag to 0 and added a KeyExtended flag in case it is needed.  Version 1.0.2 is going up to NuGet now with this fix.  Feel free to reopen this issue if I have not adequately addressed it.  Thanks!
